### ISSUE TITLE
Small issue wigh gitlab rss

### ISSUE THREAD

**Issue by mihai-satmarean** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#25]
Hi,

first of all I find the project very helpful I am using it to read some feeds since a long time.
today we want to phase off the physical machine that used to run the fetcher and we are moving to a docker-compose setup. So we followed the docker compose setup instructions/guidelines.

We managed to set up mattermost and all is fine.
We would like to receive rss feed for all activity in gitlab. but we get the following error.
Could be that we need to set up more?

Error fetching feed 'https://our-gitlab.com/dashboard/projects.atom?private_token=XXXX'
mattermost-rss_1    | 2017-04-04 07:56:36,547 - <type 'exceptions.IndexError'>
mattermost-rss_1    | Traceback (most recent call last):
mattermost-rss_1    |   File "feedfetcher.py", line 132, in fetching_feed
mattermost-rss_1    |     feed.NewTitle = d['entries'][0]['title']
mattermost-rss_1    | IndexError: list index out of range

Thank you!

**Comment by Okhoshi** [comment]
Hi @mihai-satmarean,

I did some tests on my side and the only way I could reproduce is by fetching an empty feed. Is it your case ?
If so, you can ignore this error (which will reproduce as long as your feed is empty).

**Comment by mihai-satmarean** [comment]
Hi,
first thank you for looking into it

what I have is a gitlab server with an rss activity button.
pressing the button gave me the link.
there are a lot of info in the browser when pressing the link, but pasting
the link in the rss-atom-feed produces the respective error.

let me know if I can provide more info


2017-04-05 9:32 GMT+02:00 Quentin D. <notifications@github.com>:

**Comment by dbanck** [comment]
Could you provide the environment configuration for your container? Maybe some vars got mixed up.

**Comment by Okhoshi** [comment]
Could you also provide the content of the feed at this time ? You sure can redact sensitive information, I would like to see the structure of the feed essentially.

**Comment by mihai-satmarean** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
  <title>Activity</title>
  <link href="https://our-gitlab.com/dashboard/projects.atom?private_token=49A11UpD6mh1Kq9aDEb8" rel="self" type="application/atom+xml"/>
  <link href="https://our-gitlab.com/dashboard/projects" rel="alternate" type="text/html"/>
  <id>https://our-gitlab.com/dashboard/projects</id>
  <updated>2017-04-05T10:53:29+02:00</updated>
<entry>
  <id>tag:eu-dcc-gls01.ux.dsone.3ds.com,2017-04-05:9890</id>
  <link href="https://our-gitlab.com/sites/site/commit/023dc5df9cfe32a82e673288d1fba7c22013c507"/>
  <title>SATMAREAN Mihai pushed to project branch master at sites...</title>
  <updated>2017-04-05T10:53:29+02:00</updated>
  <media:thumbnail width="40" height="40" url="https://secure.gravatar.com/avatar/e0f2da15e99ed962ccbd52a102d6dd53?s=80&amp;d=identicon"/>
  <author>
    <name>SATMAREAN Mihai </name>
    <email>mihai.satmarean@mail.com</email>
  </author>
  <summary type="xhtml">
<div xmlns="http://www.w3.org/1999/xhtml">
<p>
<strong>Mihai Cristian Satmarean</strong>
<a href="/sites/site/commit/023dc5df9cfe32a82e673288d1fba7c22013c507">(#023dc5df)</a>
<i>
at
05 Apr 10:53
</i>
</p>
<blockquote><p dir="auto">create object in site inventory in environment dev</p></blockquote>
</div>
  </summary>
</entry>

**Comment by mihai-satmarean** [comment]
@dbanck 

extract from docker-compose
```
  mattermost-rss:
    build: Rss-Atom-Feed-Integration-for-Mattermost
    environment:
      MATTERMOST_HOOK_URL: ' http://our-fqdn-url-for-mattermost-web/hooks/xxxtokenxxx'
      #MATTERMOST_CMD_TOKEN: '<your-slash-command-token>'
      RSS_SILENT_MODE: 'True'
      RSS_SHOW_NAME: 'False'
      RSS_SHOW_TITLE: 'True'
      RSS_SHOW_DESCR: 'True'
      RSS_SHOW_URL: 'False'
      RSS_VERIFY_SSL_CERT: 'False'
      RSS_SKIP_INIT_ARTICLE: 'False'
      INTEGRATION_BOT_NAME: 'RSS-Bot'
      INTEGRATION_BOT_IMG: './Rss-Atom-Feed-Integration-for-Mattermost/Rss-Atom-Feed-Integration-for-Mattermost.png'
      INTEGRATION_LISTENING_ADDR: ''
      INTEGRATION_LISTENING_PORT: '80'
      MATTERMOST_CHANNEL: 'rss-stream'
    env_file:
      - feeds.env
```

```
cat feeds.env
# RSS_FEED_<FeedName>='<FeedURL>[;<FeedLogoURL>][;<ShowName>][;<ShowTitle>][;<ShowDescription>][;<ShowURL>]'
# You can skip any parameter by directly putting a ;
RSS_FEED_CommitStrip= 'https://our-gitlab.com/dashboard/projects.atom?private_token=XXXX'
```
